apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workshop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workshop
        app_name: workshop
        project_name: workshop
    spec:
      containers:
      - image: 27.96.145.28:30500/workshop-ehyang-workshop:a6967ca-32
        imagePullPolicy: Always
        name: test
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config
          readOnly: true
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 500Mi
        env:
        - name: TZ
          value: Asia/Seoul
      volumes:
      - configMap:
          name: portal-nginx
        name: config
